# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUi(object):
    def setupUi(self, JarvisUi):
        JarvisUi.setObjectName("JarvisUi")
        JarvisUi.resize(1360, 720)
        JarvisUi.setStyleSheet("background-color: Transparent;\n"
                               "border-radius:none;")
        self.centralwidget = QtWidgets.QWidget(JarvisUi)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(-10, -60, 1371, 781))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("Black_Template.jpg"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(10, 11, 431, 311))
        self.bg_2.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                "background-color: rgb(16, 178, 214);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(450, 10, 371, 281))
        self.bg_3.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                "background-color: rgb(16, 178, 214);")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(20, 20, 411, 291))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("Iron_Template_1.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(460, 20, 341, 261))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("live.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(-20, 340, 441, 351))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("__1.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        self.gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.gif_4.setGeometry(QtCore.QRect(840, 10, 321, 221))
        self.gif_4.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                 "background-color: rgb(16, 178, 214);")
        self.gif_4.setText("")
        self.gif_4.setScaledContents(True)
        self.gif_4.setObjectName("gif_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(860, 20, 281, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Earth.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gif_5 = QtWidgets.QLabel(self.centralwidget)
        self.gif_5.setGeometry(QtCore.QRect(1250, 170, 101, 41))
        self.gif_5.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                 "background-color: rgb(16, 178, 214);")
        self.gif_5.setText("")
        self.gif_5.setPixmap(QtGui.QPixmap("Iron_Template_2.jpg"))
        self.gif_5.setScaledContents(True)
        self.gif_5.setObjectName("gif_5")
        self.gif_6 = QtWidgets.QLabel(self.centralwidget)
        self.gif_6.setGeometry(QtCore.QRect(850, 220, 481, 221))
        self.gif_6.setText("")
        self.gif_6.setPixmap(QtGui.QPixmap("initial.gif"))
        self.gif_6.setScaledContents(True)
        self.gif_6.setObjectName("gif_6")
        self.Time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(1000, 630, 331, 41))
        self.Time.setStyleSheet("color: rgb(0, 255, 255);\n"
                                "background-color: Transparent;\n"
                                "border-radius:None;")
        self.Time.setObjectName("Time")
        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(930, 590, 461, 231))
        self.bg_6.setStyleSheet("color: rgb(0, 255, 255);\n"
                                "background:Transparent;\n"
                                "border-radius:None;")
        self.bg_6.setText("")
        self.bg_6.setPixmap(QtGui.QPixmap("gyhf.jpg"))
        self.bg_6.setScaledContents(True)
        self.bg_6.setObjectName("bg_6")
        self.bg_7 = QtWidgets.QLabel(self.centralwidget)
        self.bg_7.setGeometry(QtCore.QRect(950, 410, 431, 191))
        self.bg_7.setStyleSheet("color: rgb(0, 255, 255);\n"
                                "background:Transparent;\n"
                                "border-radius:None;")
        self.bg_7.setText("")
        self.bg_7.setPixmap(QtGui.QPixmap("gyhf.jpg"))
        self.bg_7.setScaledContents(True)
        self.bg_7.setObjectName("bg_7")
        self.Time_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Time_2.setGeometry(QtCore.QRect(1010, 530, 661, 51))
        self.Time_2.setStyleSheet("color: rgb(0, 255, 255);\n"
                                  "background-color: Transparent;\n"
                                  "border-radius:None;")
        self.Time_2.setObjectName("Time_2")
        self.Time_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Time_3.setGeometry(QtCore.QRect(1000, 440, 681, 41))
        self.Time_3.setStyleSheet("color: rgb(0, 255, 255);\n"
                                  "background-color: Transparent;\n"
                                  "border-radius:None;")
        self.Time_3.setObjectName("Time_3")
        self.gif_7 = QtWidgets.QLabel(self.centralwidget)
        self.gif_7.setGeometry(QtCore.QRect(1170, 10, 181, 71))
        self.gif_7.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                 "background-color: rgb(16, 178, 214);")
        self.gif_7.setText("")
        self.gif_7.setScaledContents(True)
        self.gif_7.setObjectName("gif_7")
        self.gif_8 = QtWidgets.QLabel(self.centralwidget)
        self.gif_8.setGeometry(QtCore.QRect(1170, 90, 181, 71))
        self.gif_8.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                 "background-color: rgb(16, 178, 214);")
        self.gif_8.setText("")
        self.gif_8.setScaledContents(True)
        self.gif_8.setObjectName("gif_8")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(1180, 20, 161, 51))
        self.Start.setStyleSheet(
                                 "font: 600 24pt \"Sitka Small Semibold\";\n"
                                 "")
        self.Start.setObjectName("Start")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(1180, 100, 161, 51))
        self.exit.setStyleSheet(
                                "font: 600 24pt \"Sitka Small Semibold\";\n"
                                "")
        self.exit.setObjectName("exit")
        self.Start_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Start_2.setGeometry(QtCore.QRect(450, 300, 101, 51))
        self.Start_2.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                   "color: rgb(0, 0, 0);\n"
                                   "font: 600 24pt \"Sitka Small Semibold\";\n"
                                   "")
        self.Start_2.setObjectName("Start_2")
        self.gif_9 = QtWidgets.QLabel(self.centralwidget)
        self.gif_9.setGeometry(QtCore.QRect(440, 300, 151, 51))
        self.gif_9.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                 "background-color: rgb(16, 178, 214);")
        self.gif_9.setText("")
        self.gif_9.setScaledContents(True)
        self.gif_9.setObjectName("gif_9")
        self.gif_10 = QtWidgets.QLabel(self.centralwidget)
        self.gif_10.setGeometry(QtCore.QRect(440, 310, 371, 111))
        self.gif_10.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                  "background-color: rgb(16, 178, 214);")
        self.gif_10.setText("")
        self.gif_10.setScaledContents(True)
        self.gif_10.setObjectName("gif_10")
        self.Start_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Start_5.setGeometry(QtCore.QRect(670, 300, 101, 51))
        self.Start_5.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                   "color: rgb(0, 0, 0);\n"
                                   "font: 600 24pt \"Sitka Small Semibold\";\n"
                                   "")
        self.Start_5.setObjectName("Start_5")
        self.Start_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Start_6.setGeometry(QtCore.QRect(560, 300, 101, 51))
        self.Start_6.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                   "color: rgb(0, 0, 0);\n"
                                   "font: 600 24pt \"Sitka Small Semibold\";\n"
                                   "")
        self.Start_6.setObjectName("Start_6")
        self.gif_10.raise_()
        self.gif_9.raise_()
        self.bg_1.raise_()
        self.bg_2.raise_()
        self.bg_3.raise_()
        self.gif_1.raise_()
        self.gif_2.raise_()
        self.gif_3.raise_()
        self.gif_4.raise_()
        self.label_2.raise_()
        self.gif_5.raise_()
        self.gif_6.raise_()
        self.bg_6.raise_()
        self.Time.raise_()
        self.bg_7.raise_()
        self.Time_2.raise_()
        self.Time_3.raise_()
        self.gif_7.raise_()
        self.gif_8.raise_()
        self.Start.raise_()
        self.exit.raise_()
        self.Start_2.raise_()
        self.Start_5.raise_()
        self.Start_6.raise_()
        JarvisUi.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(JarvisUi)
        self.statusbar.setObjectName("statusbar")
        JarvisUi.setStatusBar(self.statusbar)

        self.retranslateUi(JarvisUi)
        QtCore.QMetaObject.connectSlotsByName(JarvisUi)

    def retranslateUi(self, JarvisUi):
        _translate = QtCore.QCoreApplication.translate
        JarvisUi.setWindowTitle(_translate("JarvisUi", "MainWindow"))
        self.Start.setText(_translate("JarvisUi", "Start"))
        self.exit.setText(_translate("JarvisUi", "Exit"))
        self.Start_2.setText(_translate("JarvisUi", "Youtube"))
        self.Start_5.setText(_translate("JarvisUi", "Brave"))
        self.Start_6.setText(_translate("JarvisUi", "Spotify"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    JarvisUi = QtWidgets.QMainWindow()
    ui = Ui_JarvisUi()
    ui.setupUi(JarvisUi)
    JarvisUi.show()
    sys.exit(app.exec_())
