# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Jarvis_label = QtWidgets.QLabel(Form)
        self.Jarvis_label.setGeometry(QtCore.QRect(270, 10, 271, 61))
        self.Jarvis_label.setText("")
        self.Jarvis_label.setPixmap(QtGui.QPixmap("avengero-regular (2).png"))
        self.Jarvis_label.setScaledContents(True)
        self.Jarvis_label.setObjectName("Jarvis_label")
        self.mainFrame = QtWidgets.QFrame(Form)
        self.mainFrame.setGeometry(QtCore.QRect(60, 80, 691, 491))
        font = QtGui.QFont()
        font.setBold(False)
        self.mainFrame.setFont(font)
        self.mainFrame.setAutoFillBackground(False)
        self.mainFrame.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
" border-collapse: collapse;\n"
"gridline-color: rgb(255, 255, 255);")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.usrname = QtWidgets.QLineEdit(self.mainFrame)
        self.usrname.setGeometry(QtCore.QRect(180, 30, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.usrname.setFont(font)
        self.usrname.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"")
        self.usrname.setStyleSheet("color:white;")
        font.setPointSize(20)
        self.usrname.setText("")
        self.usrname.setObjectName("usrname")
        self.password = QtWidgets.QLineEdit(self.mainFrame)
        self.password.setGeometry(QtCore.QRect(180, 130, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.password.setStyleSheet("color:white;")
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.login_button = QtWidgets.QPushButton(self.mainFrame)
        self.login_button.setGeometry(QtCore.QRect(280, 220, 161, 61))
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setStyleSheet("border-image: url(hello.png);\n"
"border-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color:transparent;")
        self.login_button.setText("")
        self.login_button.setObjectName("login_button")
        self.retry_butt = QtWidgets.QPushButton(self.mainFrame)
        self.retry_butt.setGeometry(QtCore.QRect(20, 410, 161, 61))
        self.retry_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.retry_butt.setStyleSheet("border-image: url(retry.png);\n"
"background-color:transparent;")
        self.retry_butt.setText("")
        self.retry_butt.setObjectName("retry_butt")
        
        self.exit_but = QtWidgets.QPushButton(self.mainFrame)
        self.exit_but.setGeometry(QtCore.QRect(510, 410, 161, 61))
        self.exit_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_but.setStyleSheet("border-image: url(avengero-regular.png);\n"
"background-color:transparent;")
        self.exit_but.setText("")
        self.exit_but.setObjectName("exit_but")
        self.wrong = QtWidgets.QLabel(self.mainFrame)
        self.wrong.setGeometry(QtCore.QRect(170, 20, 401, 271))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.wrong.setFont(font)
        self.wrong.setStyleSheet("border:0px")
        self.wrong.setText("")
        self.wrong.setPixmap(QtGui.QPixmap("giphy.gif"))
        self.wrong.setScaledContents(True)
        self.wrong.setObjectName("wrong")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.usrname.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; color:#ffffff;\">USERNAME</span></p></body></html>"))
        self.usrname.setPlaceholderText(_translate("Form", "USERNAME"))
        self.password.setPlaceholderText(_translate("Form", "PASSWORD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
